baseURL: "https://lumma-cs.github.io/"
languageCode: "en-us"
title: "Lumma Creative Studio"
theme: "PaperMod"

outputs:
  home:
    - HTML


params:
  defaultTheme: light
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
